### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by lazka** [flathub/uk.co.ibboard.cawbird#3]
```
flatpak run uk.co.ibboard.cawbird     
Unable to init server: Could not connect: Connection refused

(cawbird:3): Gtk-WARNING **: 11:15:00.348: cannot open display: 
```

All my other gtk flatpak apps work. I only get this error with xorg, under wayland it starts fine.

**Comment by p1u3o** [comment]
What desktop environment and distro?

**Comment by lazka** [comment]
Gnome Shell, Debian sid.

**Comment by bilelmoussaoui** [comment]
I guess you're missing some env variable on the x11 session that makes flatpak not aware of it and doesn't fallback to x11. You can check that by running `flatpak run --nosocket=fallback-x11 --socket=x11 uk.co.ibboard.cawbird`

**Comment by IBBoard** [comment]
Is this fixed now?

**Comment by lazka** [comment]
I think so, thanks!
